const quotes = [
    "Your mom is a finger food",
    "Poop… Fart… Poop fart in my butt",
    "I dislocated my tailbone",
    "Your moms butt nevermore nevermore quoth the raven",
    "My wife left me and went to alaska to marry steve harvey",
    "I have several wives one of them ran away nevermore nevermore quoth the raven",
    "I have boils on my skin",
    "Mr. P: \"What? Are you shoe shopping?\" Hayden: \"It was Robert\".",
    "I'm gonna marry your cousin if she plays pixel gun 3D",
    "*drumming on kneecaps intensifies*",
    "I'm gonna make jerky out of you",
    "Gonna eat you up",
    "I'm brodying it",
    "I'm gonna breakfast your body",
    "Your body is my breakfast",
    "It's Jonas day",
    "Hehehehehehehehehe",
    "My fee is 100 pogs",
    "Thank you for attending my TED Talk Smiffy Pookie",
    "F",
    "Little girls are like when you go to the store and you pick the juiciest fruit by squeezing",
    "Yo he just like me frfr",
    "I need a liquid in my mouth",
    "Im back on Earth",
    "Merry Christmas",
    "Guys! Do not go to bed early at 3AM!",
    "I have new screenshots i'm not allowed to send 😊",
    "I never pegged you as a pegging guy",
    "Blud regained his typing skill",
    "Steven your friends are cringe",
    "Your perception skills are underdeveloped",
    "Fishbot bad. Im better than you",
    "What abt ur mom?",
    "Lets just pretend it doesn't exist",
    "Stevens the one with the skill issue. I rendered his current version of fishbot obsolete in a matter of seconds",
    "Disregard all my previous words",
    "8 presidents have died in office",
    "Jesse's gay so there's gotta be at least 3% aids",
    "I've been advised by my lawyers to affirm to you that steven is indeed not a homosexual",
    "Unless you get hit by a bus of course",
    "Nifty",
    "Who's Mason? OHHH YOU MEAN STEVEN!",
    "Isaiah we will track down members of your family and ask them for the clip of you singing california girls",
    "Isaiah we will be talking to your mother tomorrow...",
    "Tell us more about your mother Connor",
    "I can confirm I have an official Mr. Collins Christmas Card",
    "This Pavlick character sounds great 👍",
    "Why did Mr. Smith send me \"Do not start abusing teams…\" this morning?",
    "What that nose do?",
    "Five night at roberr! Gyatt where you wanna be? I am a sigma. I am skibidi",
    "Diet snowda",
    "SHAPES THAT GO!! SHAPES THAT GO!! SHAPES THAT GO!!",
    "Why are you calling him mason?? You guys are weird smh",
    "Good night edge long and prosperous",
    "Check your dms soy boy",
    "I must become Godot God!",
    "I dwinking grapfroot sody pop",
    "A little kink in the sink",
    "Im gonna make a chicken muncher game",
    "What about the classic ball fart?",
    "The rapture is outside my window",
    "I'm a different breed of IT kid",
    "Greetings my friends",
    "Very early in development (PWEESE DON'T MAKE FUN OF ME! I'M A SENSITIVE ANIME GIRL AND I HAVE VEWY SENSITIVE FEEWING UWU)",
    "Vietnam Napalm",
    "Bye bye rober",
    "metroifd",
    "Cream machine",
    "I sure am a naughty naughty boy",
    "Most affirmatively",
    "I mean",
    "No way jose",
    "AI MOMENT",
    "Im dating connors mom",
    "No more thickness inside his body 😭",
    "The chocolate is just too gerbil-like for my tastes",
    "OH NOES!",
    "I am acutely aware",
    "Yass queen",
    "I love researching Roberts relatives",
    "I dont want a gyatt for rizzmas",
    "What happened to little steven?",
    "Skibidi rizzler gyatt ohio sussy baka fortnite amoungus toilet moment?",
    "*passes away peacefully",
    "Steven needs to trademark that posture",
    "I GOT TO HAVE A GYATT",
    "This is a gyatt free edge zone. Take those sussy balls of yours somewhere else",
    "No, petah! Stop! I'm gonna poop!",
    "Ballbasket moment",
    "El pupitre moment",
    "STOP FISTING I MEAN FISTING I MEAN FISTING I MEAN FISHING ME!",
    "Remove deez nuts",
    "I AM BACK!",
    "Joey you're an incel",
    "Blud doesnt even know who shaun donnally is.",
    "Looks like we have a fellow reddit user",
    "Gen alpha going places",
    "Oh baby a triple",
    "Connor your mom is hot",
    "No edging until eptember",
    "Foo",
    "Being black is racist",
    "I want to feel it in every bone",
    "First I rizz your brother now I rizz you",
    "Piggies",
    "Make maps slave",
    "Ball + Ball = Balls",
    "I had a momentary lapse of judgment",
    "Farewell",
    "Im in my gooning garb rn",
    "Im gonna suck your balls dry",
    "Just threw up",
    "Blud has been stalking me",
    "IHOP edging skibidi rizzler moment",
    "Joey is white",
    "Robert why are you putting this here this is my channel you mexican",
    "I shall obama my balls too",
    "I go to alaska for shampoo samples",
    "Fortnite my balls",
    "Steven im gonna devour you tomorrow at break",
    "You have me added on feet finder",
    "I thought you liked feet?",
    "What? You kids don't like feet",
    "I will be staying home tomorrow to play metroid",
    "Blud me serious I will fish you with my giant throbbing fish",
    "It was not blackmail. Just a simple trade offer",
    "Slay bae",
    "My mom told me I shouldn't be gaming with Mr. Smith cuz its not professional 😭",
    "Is Steven rich now? Is he gonna own us now?",
    "You want this dog?",
    "Huggy wuggy",
    "Gallbladder",
    "Me when I pirate pal world because I don't want to support the capitalist monopolistic empire (i don't feel like asking my mommy for moneys)",
    "2 bacon lettuce tomato?",
    "Welcome to fortnite town!",
    "Hop fof forman",
    "How to canonically eat pizza?",
    "People who use instagram reels only use it to watch goofy things and people breaking bones",
    "My face when we do the CBT in english class",
    "I started learning JS in the 4th grade",
    "Steven this further proves how much you need to touch grass",
    "Goofballin",
    "Robert ambatakum",
    "THE EVE OF NNN IS UPON US… I already failed",
    "I have popcorn butter stains on my shirt",
    "What are you trying to brute force?",
    "Five frivolous evenings at freddy fazbears pizza restaurant establishment",
    "My last couple braincells are yours",
    "Cylinder doesnt equal cylinder",
    "Not coding solitaire screw you",
    "Just say JS you idiot",
    "Yeppers to peppers",
    "I pranked his wife",
    "Sam the speed at which you reacted, deleted, and timed me out is definitve proof you were born and raised a discord mod",
    "Isaiah is giving major Reggie Fils Aime vibes rn",
    "I'M FRIENDS WITH A VIKING!!!",
    "Take them socks off boy",
    "I ate 50 cheez-itz off the floor",
    "Big meaty claws",
    "Shut your dirty little mouth",
    "I put robers address in chat",
    "Who are you and why are you in my house?",
    "Four score and seven years ago our fathers brought forth",
    "No",
    "bad news bears guys",
    "It okay",
    "I'm playing Metroid at school!!!",
    "Calamity ganon!",
    "We need smifftrap",
    "I've had a good chuckle over that one",
    "Sam you're the kind of guy to listen to math rock",
    "Jack black is in the new formbar",
    "Oh you playin' minecraft",
    "You're a discord mod sam",
    "MaCAFEE!",
    "CHEESIUM!!",
    "Dasty naddy",
    "Java is the devil's language",
    "Let's fight until one of us gets pregnant",
    "Gobulent Goober",
    "You is among us",
    "Dirty chemicals inside me",
    "Stimulate me father",
    "Connor mom definitely a w",
    "I found Mr. Smith's house on zillow! So spacious!",
    "The holy juices my son and weep",
    "Video gaming inside me",
    "I'm not gonna read this",
    "I'm better than you",
    "Joey you're an icel",
    "Legend has it I still need milk",
    "I'm moving to Mumbai and becoming a shoe maker",
    "If any of you are my father please show your face",
    "Is it because you were raised by rednecks",
    "No, it was because of cacashooter",
    "I told Smith you were actively trying to destroy him now he lives in fear of you Steven",
    "Mr. Smith blocked me",
    "We need a minigame where you deliver cacashooter to Smith",
    "Relax its just a abnormally large Smith moment soon he'll reach post-Smith clarity",
    "Basically this kid in bachas class is using the formbar and Mr. Smith keeps coming around sniffing for him",
    "We must conjoin!",
    "Welcome to the bagel jungle we got cream cheese",
    "MR SMITH WHY DID YOU MAKE YOUR CODE SO CRINGE",
    "When's my watch mojo video?",
    "Oasis is a great band",
    "So spacious how many square feet is it?",
    "Actually scratch that I need a 36''x16'' poster of connor's mom",
    "I'm gonna delete the code and start again guys",
    "Guys we're doing it in godot",
    "You should be mapping not playing wii sports",
    "Zeke show me the pics",
    "My grandma was right I am a very handsome young man",
    "Sucking in your cheeks give you exponential jawline growth",
    "Man I hate my ex she took my house and the kids I just want to see my son",
    "Man these teachers need to step up their pog game",
    "Drive us to chuck e cheese",
    "HIT THE GRIDDY!!",
    "D drive for DEEZ NUTS",
    "I miss the days when we gave each other candy on valentines day. Now people give each other STDs",
    "Robert",
    "I want your cousin to cook me a meal",
    "Roberts second cousins is such a baddie",
    "She makes my hormones go crazy!",
    "Dude Robert your cousin is so hot",
    "I mean I would never do anything with her but she's hot",
    "Robert's second cousin makes me tingle on the inside!",
    "I'M HAVING A MENTAL BREAKDOWN",
    "TEA TIME",
    "CALL THE DOCTOR MATE",
    "WAIT… oa-SUS! NOOOOOOOOOOOOOOOOOOOOO THE IMPOSTER",
    "GOD SAVE THE QUEEN",
    "Robert I'm making a song about your cousin",
    "God I love ChatGPT",
    "I think ChatGPT wrote me an incest poem",
    "That doc is going to be a New York Times best seller someday",
    "How dare you call my doc cringe",
    "UWU",
    "I need me a woman who plays pixel gun 3D",
    "It's russian propaganda",
    "THE YOUNGER THE BETTER",
    "THE CLOSER IN BLOOD THE BETTER",
    "If she's four she's ready to explore",
    "Yessirry bob",
    "I'm eating pretzels off my belly",
    "Steven is lying just like he lied about the weapons of mass destruction in Iraq",
    "Yes I am sigma",
    "I want you so bad",
    "Wake up in the morning doing the griddy",
    "Robert",
    "This is what ray would look like if ray got a low taper fade",
    "Daddys coming",
    "When Roberts cousin hears my song shes gonna say \"Oh my god now my ovaries are screaming\"",
    "When are you gonna kiss me?",
    "Steven does not care about the consequences of his actions",
    "Tooty frooty",
    "Oh rudy!",
    "Say gex",
    "When the juices are flowing there is no forgoing",
    "My birthday is in a few weeks and I would really appreciate if you would be so gracious as to allow me to become your sigma",
    "JFK inside jon",
    "When that clock strikes half past six",
    "Contrary to popular belief it is the gay part",
    "Gay people was an inside job",
    "I don't know why but the idea of a slave owner whipping his slave because he won't do the thug shake for him is extremely comical to me.",
    "I just have a little feeling that that document is gonna come back to haunt me at some point within the next 20 years",
    "My leg pits are stinky...",
    "C'mon boy you gonna do that thug shake *whip cracks*",
    "my feet smell funny",
    "Babe can we try nasal",
    "My brain is like spongebob if spongebob was a cement mixer",
    "Mario movie 2 with gay mario and weegy segs scene?",
    "You must be the guy from 2 and a half men",
    "Get down make lovew",
    "You have a quote queue list?",
    "Pluh gogint oog gdc tmr??",
    "YOOOOO STEVEN WENT OUTSIDE",
    "Who carried you to bed?",
    "Dont go outside thats where the black people live",
    "My children I have the vid",
    "The big C",
    "Corona lite",
    "Eirwuoiouewiuo",
    "Ban this *grabs scrotum*",
    "This is a slightly less developed version of me enjoying a salad sandwich at olive garden",
    "Y'all remember when that Arby's cashier milked me good and dry on Cinco De Mayo many moons ago",
    "I love being white",
    "I could read but it never struck me to read in a video game",
    "I had NSMBW but my brain wasn't developed enough to know to flip the wiimote so I thought the controls were weird so we got rid of it",
    "He doesn't want to upset daddy miyamoto",
    "Once you go black you never go back",
    "When are we having that naked tickle fight?",
    "We have to talk about the banana prices",
    "No",
    "I like to demolish your flesh with my molars",
    "Im Mr. coke meister",
    "If you notice little white nuggets in the back of your mouth you most likely have ligma",
    "It feels so good to be bad",
    "Put your little black hands in the bag",
    "My mating call is going up to random women in the hallway jumping up and down and screaming WOOOOO! sure I may get beaten up by their boyfriends but it works.",
    "If my doc is breaking bad then your doc is better call saul (this is not true as mine came first)",
    "hey baby",
    "My brother has a dash of ‘tism and a ton of adhd",
    "I have just farted inside of my pantaloons.",
    "I'm pregnant with your baby",
    "Empty the compartments of your pantaloons",
    "I got the illuminati in my mouth ew smelly",
    "OH STEVEN! Yeah he's a drug addict bro",
    "I don't have any context to this cause I don't know who the heck mason is",
    "I like puss!",
    "OH YEAH THAT'S DEFINITELY CHINESE",
    "Hands off daddy-o",
    "Hello dearest Isaiah!",
    "Hey Isaiah",
    "You so outta pocket little skibidi",
    "You know there's a muscle you have that can hold back the fluids?",
    "Edward! You da man, Edward!",
    "When I want to not laugh I just think about my dying cat",
    "My sisters both agree that my mew was good",
    "UGH! I just edged",
    "Yo! When's the second coming of Jesus? I wanna mew for him",
    "Jesus is going to take one look at my jaw and say \"WOW! You have a superior jawline you're going to heaven!\"",
    "None, I am the lone wolf sigma male",
    "Mewing moment",
    "She said she was 10",
    "Such a little gooty",
    "You know when your diaper gets soggy?",
    "You show dyslexic tendencies",
    "I just creamed my jeans to the thought of that",
    "Blasted! You've foiled my plan! And I would have gotten away with it if it wasn't for you meddling kids!",
    "my nipples are so hard",
    "THATS MY HOUSE",
    "She can't take it like my grandma can",
    "Fo-sho daddy-o",
    "This is why I hate edge",
    "this is funny because people who like anime are actually unstable because they are gay incels that we should just let mother nature take its course instead of wasting medication on them. At least they won't be able to spread their genes so they will all die off at some point.",
    "STEVEN!",
    "Gotta make a move to a town that's right for me.",
    "I drank diet soda for lunch it made me silly",
    "GYATT!",
    "ummy orse ock",
    "I get anti-semitic when I don't have my Diet Coke in the morning.",
    "Yo Connor I went to your house and saw your mom it was awesome",
    "SODA!!!!",
    "Salisbury steak",
    "SVEN!",
    "Yo remember that time steven made a bomb threat in 3rd grade shiz was crazy",
    "when the day comes to a close the socks come off hairy and larger than average for my age I reach my hand out to engage I firmly grasp it sweaty and hairy",
    "T'was the night before rizzmas",
    "SIGMA!",
    "There's so many Mr. Smith quotes that should be on a shirt",
    "Yes kids are stupid",
    "I remember doing css in 5th grade and I got told on for hacking",
    "Eat food",
    "anime cringe",
    "cringe",
    "non-sigma",
    "make sure to put it on GitHub so I can look at it and make fun of you in my head",
    "playing wii is for good boys",
    "im such a sigga- i mean sigma",
    "femboy monday!",
    "chewsday",
    "bloody chewsd'ay",
    "oasis reunion bruv innit",
    "we're talking about dads funeral",
    "one time my teacher was wearing a yamaka and told us the doctor made her wear it because she got hurt leaning back in the chair too far",
    "No, petah! Stop! I'm a virgin",
    "I don't think you have a right to an opinion",
    "Fard.",
    "I eated it all sowwy",
    "Project SODA!!!",
    "This is my face when I have to start all over again. Hah hah hah hah hah!",
    "why did you do that?",
    "DO YOU KNOW WHO I AM???",
    "Project STEVEN!",
    "Deez nuth",
    "St st st st sts st sty sty st sty sty sty styrofoam!",
    "How does that happen??",
    "please don't touch us",
    "You bumbling buffons! I am trying to take the CIW pretest but I cannot concentrate with all the racket!",
    "Sigma male on the Ohio streets i always bring the heat and meat",
    "SCHTEVEN!",
    "My brain hurtie the other way. Too easy. Complete waste on my time",
    "I've been brown nosing since Nixon",
    "He's committed social atrocities such as beng short",
    "Ew it smells like stinky mustard in here",
    "I have to mew but you just have a sleek jawline. Congratulations stevn"
];

const siteExclusiveQuotes = [
    "NAME YOUR COMMITS, YOU MONKEY",
    "ADD MORE EXCLUSIVE QUOTES",
    "it's perfectly natural to be addicted to minecraft sex question mark?",
    "read up frickers",
    "YOU GAVE JESSE SPACE AIDS",
    'You know what you did, you dirty little rat boy.',
    '*cringe dancing* that\'s the happy birthday dance!'
];