const quotes = [
['I want to throw cheese on Joe Rogans head - Sam', 'sam'],
['No, dont make fronk watch talk tuah you\'ll die - Penny', 'penny'],
['My stripper name is the gravy boat - Sam', 'sam'],
['It was more of the constipation elixir - Sam', 'sam'],
['Just watch joey be like spidered on top of Isaiah - Sam', 'sam'],
['Youre getting a purple snap on snapchat from hayden - Sam', 'sam'],
['Hayden wants to give her his little frobenius???? - Isaiah', 'isaiah'],
['She doodle on my bob till I me-hoy-me-noy - Sam', 'sam'],
['She got me making noises like doodlebob - Sam', 'sam'],
['WHAT TYPE OF COLOR IS PINKLE???? - Mr. Money', 'jack'],
['I\'m hayden. Coding. Squatter sim. Soda!!!! Blackmail. - Lynn', 'lynn'],
['Tell them how you lied about the weapons of mass destruction in Iraq! - Isaiah', 'isaiah'],
['Oh yeah. Oh yeah. Oh yeah. Oh yeah. Mmm… - Lynn', 'lynn'],
['Shut up before I kiss you on the lips. -Jesse', 'jesse'],
['YOU SQUIRTED ALL OVER MY HEADPHONES - Bryce', 'bryce'],
['You\'re older than me it\'s okay - Isaiah', 'isaiah'],
['Wait, your name is fard? - Hayden', 'hayden'],
['SINGING KILLED MY GRANDMA, OKAY? - Isaiah', 'isaiah'],
['I am so sorry for the extreme amount of brain damage you have - Jesse', 'jesse'],
['You wanna fizzy my faz? - Mr. Yeager (This message is sponsored by Fazbear incorporated) ', 'connor'],
['Everytime I say Phasmophobia I think Fazbear phobia - Jesse', 'jesse'],
['I am not sexually attracted to Pedro Pascal, he is simply my daddy - Jesse', 'jesse'],
['I lost my balls in the war and thought it would be easier to transition - Jesse', 'jesse'],
['I\'m Freakbob. I freak all over the Freakini Bottom - Jesse', 'jesse'],
['The stylus is going in my urethra! - Jesse', 'jesse'],
['I gotta clap back harder, but it\'s okay. I can clap your cheeks. - Jesse', 'jesse'],
['I want Malcom X to dick me down. - Jesse', 'jesse'],
['Oh, you\'re being attacked and killed and murdered? Too bad. Thug it out. - Jesse', 'jesse'],
[' British people waking up and realizing they have to do the accent all day - Jesse', 'jesse'],
['He\'s not really weird, he\'s just extraordinarily messed up in the head - Jesse', 'jesse'],
['I\'m an independent manwhore. I whore myself out without a pimp - Jesse', 'jesse'],
['She\'s very corn fed! - Jesse', 'jesse'],
['Yeah get to digging Connor you digger - John Showman', 'john'],
['Day is never finished, master got me working, someday master set me free - Mr. Yeager', 'connor'],
['IM DYSLEXIC COLOR BOY! -Penny', 'penny'],
['You have contributed nothing except for looking at weird women on your computer - Penny', 'penny'],
['Grandma Nutt freaky? - Sam', 'sam'],
['I hope Mr. Smith checks his Sigma Mail - Steven', 'steven'],
['“Jesse, you look like someone to eat bananas for the shape and not the taste” “Sam, I\'m fucking gay.” - Jesse & Sam', 'sam'],
['You\'re right, I do got a squirt. Do you know where the squirter is? - Chicken Sandwich', 'tyler'],
['WE GOT REACT AT HOME! … It doesn\'t work - Hayden', 'hayden']
]

const siteExclusiveQuotes = [
['The soda just goes right through him. He has to go to the bathroom. - Mr. Yeager', 'connor'],
['Woke up, Mixter Freethem. Woke up and smell the pronoun. - Lynn', 'lynn'],
['Lemme see those BAKED BEANS - Chicken Sandwich', 'tyler'],
['I\'m a 17 year old boy in a 17 year old boy\'s body. - Chicken Sandwich', 'tyler'],
['I have the soul of someone my age - Chicken Sandwich', 'tyler'],
['I am glad my uber-autism and extremely low social skills have contributed to your project - Chicken Sandwich', 'tyler'],
['Me swinging my frank around - Jesse', 'jesse'],
['I\'m not curious. I know what I like. I like DICK', 'jesse'],
['You wanna know how I got this lazy eye? Do you wanna know how I gained all this WEIGHT - Chicken Sandwich', 'tyler']
]
//amogus sus